version: "3"

services:

#   # Asynchronous Queue
#   rabbitmq:
#     image: "rabbitmq:3-management"
#     ports:
#       - "5672:5672"
#       - "15672:15672"
#     # volumes:
#     #   - 'rabbitmq_data:/data'

#     volumes:
#         - rabbitmq_data

  database:
    image: mysql
    ports:
        - "3306:3306"
    command: 
        --sort_buffer_size=100000000
        # --init-file /data/application/init.sql
    volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        MYSQL_ROOT_USER: admin
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_USER: user
        MYSQL_PASSWORD: userpassword

  server:

    # Location of Dockerfile if needed
    build: server
    ports:
      - "5000:5000"