version: "3.8"

services:

  inference-engine:
    # Location of Dockerfile if needed
    build: 
        context: .
        dockerfile: ./inference_engine/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
      - database
    # ports:
    #   - "5672:5672"
    networks:
      - webnet

  # Asynchronous Queue
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    # volumes:
    #   - 'rabbitmq_data:/data'
    hostname: rabbitmq
    volumes:
        - rabbitmq_data
    networks:
      - webnet

  database:
    image: mysql
    hostname: database
    ports:
        - "3306:3306"
    command: 
        --sort_buffer_size=100000000
        # --init-file /data/application/init.sql
    volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        MYSQL_ROOT_USER: admin
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_USER: user
        MYSQL_PASSWORD: userpassword
    
    networks:
      - webnet

#   server:
#     # Location of Dockerfile if needed
#     build: 
#         context: .
#         dockerfile: ./server/Dockerfile
#     ports:
#       - "5000:5000"
#     depends_on:
#       - rabbitmq
#       - database



networks:
  webnet: