apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-engine
  template:
    metadata:
      labels:
        app: rabbitmq-engine
    spec:
      hostname: rabbitmq
      containers:
      - name: rabbitmq-engine
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672

---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: rabbitmq                 # hostname of resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
  selector:
    app: rabbitmq-engine         # Map any pod with label `app=rabbitmq-engine` to this service