apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pred-server-deployment
  labels:
    app: ml-pred-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-pred-server
  template:
    metadata:
      labels:
        app: ml-pred-server
    spec:
      containers:
      - name: ml-pred-server
        image: gcr.io/single-inquiry-185401/ml_pred_server
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: ml-pred-server-service   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: ml-pred-server         # Map any pod with label `app=ml-pred-server` to this service